support for sendMediaGroup; parameter -h for hostname

diff --git a/telegram b/telegram
--- a/telegram
+++ b/telegram
@@ -13,7 +13,7 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-VERSION="0.4"
+VERSION="0.6"
 TOKEN=""
 CHATS=()
 DEBUG=false
@@ -21,6 +21,7 @@ DRY_RUN=false
 
 IMAGE_FILE=""
 DOCUMENT_FILE=""
+VIDEO_FILE=""
 PARSE_MODE=""
 CODE_MODE=0
 CRON_MODE=0
@@ -29,8 +30,9 @@ TITLE=""
 DISABLE_WEB_PAGE_PREVIEW=false
 DISABLE_NOTIFICATION=false
 
-URL="https://api.telegram.org/bot"
-FILE_URL="https://api.telegram.org/file/bot"
+HOST="https://api.telegram.org"
+URL="$HOST/bot"
+FILE_URL="$HOST/file/bot"
 CURL_OPTIONS="-s"
 
 HAS_JQ=false
@@ -45,7 +47,9 @@ function help {
 	echo "    -t <TOKEN>       Telegram bot token to use. See ENVIRONMENT for more information."
 	echo "    -c <CHAT_ID>     Chat to use as recipient. Can be given more than once. See ENVIRONMENT for more information."
 	echo "    -f <FILE>        Sends file."
+	echo "    -F <FILE>        Sends file album."
 	echo "    -i <FILE>        Sends file as image. This will fail if the file isn't an actual image file."
+	echo "    -V <FILE>        Sends file as video."
 	echo "    -M               Enables Markdown processing at telegram."
 	echo "    -H               Enables HTML processing at telegram."
 	echo "    -C               Sends text as monospace code. Useful when piping command outputs into this tool."
@@ -59,6 +63,7 @@ function help {
 	echo "    -N               Diables notifications on clients. Users will receive a notification with no sound."
 	echo "                     Can also be set in config as TELEGRAM_DISABLE_NOTIFICATION=true (see ENVIRONMENT)"
 	echo "    -m               Outputs the last received message. Format is: <Message ID> <Sender ID> <Chat ID> <Text>"
+	echo "    -h <HOST>        Host of Telegram Bot API. Default is https://api.telegram.org. Useful when you host own"
 	echo
 	echo "DEBUGGING OPTIONS are:"
 	echo "    -v               Display lots of more or less useful information."
@@ -68,12 +73,13 @@ function help {
 	echo "Message can be '-', in that case STDIN will be used."
 	echo
 	echo "ENVIRONMENT"
-	echo "    TOKEN and CHAT_ID are required. You can set them in four different ways:"
+	echo "    TOKEN and CHAT_ID are required. You can set them in six different ways:"
 	echo "      1) globally in /etc/telegram.sh.conf"
 	echo "      2) user-local in ~/.telegram.sh"
 	echo "      3) user-local in ~/.telegram.sh.conf"
-	echo "      4) via environment variables TELEGRAM_TOKEN and TELEGRAM_CHAT"
-	echo "      5) via options -t and -c"
+	echo "      4) relative to this script in `dirname "$0"`/.telegram.sh.conf"
+	echo "      5) via environment variables TELEGRAM_TOKEN and TELEGRAM_CHAT"
+	echo "      6) via options -t and -c"
 	echo "    Later methods overwrite earlier settings, so you can easily override global settings."
 	echo "    Please be aware that you shuld keep your telegram token secret!"
 	echo
@@ -186,11 +192,18 @@ function check_file {
 		echo "The file $1 does not exist."
 		exit 1
 	fi
-
-	size=$(stat -c%s "$1")
-	if (( size > 52428800 )); then
-		echo "File $1 is breaking the file size limit imposed on Telegram bots (currently 50MB)."
-		exit 1
+	
+	case "$(uname -s)" in
+		Darwin*) # OSX
+			size=$(stat -f%z "$1");;
+		*)
+			size=$(stat --printf="%s" "$1");;
+	esac
+	if [ "$HOST" = "https://api.telegram.org" ]; then
+		if (( size > 52428800 )); then
+			echo "File $1 is breaking the file size limit imposed on Telegram bots (currently 50MB)."
+			exit 1
+		fi
 	fi
 }
 
@@ -202,7 +215,7 @@ function escapeMarkdown {
 	echo "$res"
 }
 
-while getopts "t:c:i:f:MHCrhlvjnRmDNT:" opt; do
+while getopts "h:F:t:c:i:f:V:MHCrhlvjnRmDNT:" opt; do
 	case $opt in
 		t)
 			TOKEN="$OPTARG"
@@ -215,6 +228,16 @@ while getopts "t:c:i:f:MHCrhlvjnRmDNT:" opt; do
 			;;
 		f)
 			DOCUMENT_FILE="$OPTARG"
+			;;
+		F)
+			if [ -z "$DOCUMENT_FILES" ]; then
+				DOCUMENT_FILES=( "$OPTARG" )
+			else
+				DOCUMENT_FILES+=( "$OPTARG" )
+			fi
+			;;
+		V)
+			VIDEO_FILE="$OPTARG"
 			;;
 		M)
 			PARSE_MODE="Markdown"
@@ -257,6 +280,11 @@ while getopts "t:c:i:f:MHCrhlvjnRmDNT:" opt; do
 		T)
 			TITLE="$OPTARG"
 			;;
+		h)
+			HOST="$OPTARG"
+			URL="$HOST/bot"
+			FILE_URL="$HOST/file/bot"
+			;;
 		?|h)
 			help
 			;;
@@ -290,6 +318,7 @@ log "Importing config file(s)..."
 [ -r /etc/telegram.sh.conf ] && source /etc/telegram.sh.conf
 [ -r ~/.telegram.sh ] && source ~/.telegram.sh
 [ -r ~/.telegram.sh.conf ] && source ~/.telegram.sh.conf
+[ -r `dirname $0`/.telegram.sh.conf ] && source `dirname $0`/.telegram.sh.conf
 
 [ -z "$TOKEN" ] && TOKEN=$TELEGRAM_TOKEN
 [ ${#CHATS[@]} -eq 0 ] && CHATS=($TELEGRAM_CHAT)
@@ -386,8 +415,8 @@ if [ -n "$TITLE" ]; then
 	fi
 fi
 
-if [ -z "$TEXT" ] && [ -z "$DOCUMENT_FILE" ] && [ -z "$IMAGE_FILE" ]; then
-	echo "Neither text nor image or other file given."
+if [ -z "$TEXT" ] && [ -z "$DOCUMENT_FILE" ] && [ -z "$VIDEO_FILE" ] && [ -z "$IMAGE_FILE" ] && [ -z "$DOCUMENT_FILES" ] ; then
+	echo "Neither text nor image nor video or other file given."
 	exit 1
 fi
 
@@ -395,14 +424,62 @@ if [ -n "$DOCUMENT_FILE" ] && [ -n "$IMAGE_FILE" ]; then
 	echo "You can't send a file AND an image at the same time."
 	exit 1
 fi
+if [ -n "$DOCUMENT_FILE" ] && [ -n "$VIDEO_FILE" ]; then
+	echo "You can't send a file AND an video at the same time."
+	exit 1
+fi
+if [ -n "$IMAGE_FILE" ] && [ -n "$VIDEO_FILE" ]; then
+	echo "You can't send an image AND a video at the same time."
+	exit 1
+fi
+
 
 [ -n "$PARSE_MODE" ] && CURL_OPTIONS="$CURL_OPTIONS --form-string parse_mode=$PARSE_MODE"
-if [ -n "$DOCUMENT_FILE" ]; then
+PASS_CAPTION=true
+if [ -n "$DOCUMENT_FILES" ]; then
+
+	MEDIA_JSON="["
+	comma=""
+
+	CNT=${#DOCUMENT_FILES[@]}
+	for (( i=0; i<${CNT}; i++ ));
+	do
+		FILE="${DOCUMENT_FILES[$i]}"
+		check_file $FILE
+		CURL_OPTIONS="$CURL_OPTIONS --form file$i=@\"$FILE\""
+		MEDIA_JSON="$MEDIA_JSON$comma{\"type\":\"document\",\"media\":\"attach://file$i\""
+		if [ $i = "$(( CNT - 1))" ]; then
+			if [ "$HAS_JQ" = false ]; then
+				echo "You need to have jq installed in order to be able to send media groups (to put caption in it)."
+				exit 1
+			fi
+
+			CAPTION=$(echo -n "$TEXT" | jq -Rsa .)
+			MEDIA_JSON="$MEDIA_JSON,\"caption\":$CAPTION,\"parse_mode\":\"$PARSE_MODE\"}"
+		else
+			MEDIA_JSON="$MEDIA_JSON}"
+		fi
+		comma=","
+	done
+
+	PASS_CAPTION=false
+
+	MEDIA_JSON="$MEDIA_JSON]"
+	CURL_OPTIONS="$CURL_OPTIONS --form media=<-"
+
+	METHOD="sendMediaGroup"
+elif [ -n "$DOCUMENT_FILE" ]; then
 	check_file "$DOCUMENT_FILE"
 
 	CURL_OPTIONS="$CURL_OPTIONS --form document=@\"$DOCUMENT_FILE\""
 	CURL_OPTIONS="$CURL_OPTIONS --form caption=<-"
 	METHOD="sendDocument"
+elif [ -n "$VIDEO_FILE" ]; then
+	check_file "$VIDEO_FILE"
+
+	CURL_OPTIONS="$CURL_OPTIONS --form video=@\"$VIDEO_FILE\""
+	CURL_OPTIONS="$CURL_OPTIONS --form caption=<-"
+	METHOD="sendVideo"
 elif [ -n "$IMAGE_FILE" ]; then
 	check_file "$IMAGE_FILE"
 	CURL_OPTIONS="$CURL_OPTIONS --form photo=@\"$IMAGE_FILE\""
@@ -418,6 +495,8 @@ fi
 
 for id in "${CHATS[@]}"; do
 	MY_CURL_OPTIONS="$CURL_OPTIONS --form-string chat_id=$id $URL$TOKEN/$METHOD"
+	
+	log "curl $MY_CURL_OPTIONS <<< \"$MEDIA_JSON\""
 	if [ "$DRY_RUN" = true ]; then
 		echo "Executing: curl $MY_CURL_OPTIONS"
 		echo "     Text: $TEXT"
@@ -425,8 +504,13 @@ for id in "${CHATS[@]}"; do
 		status=0
 		response='{"ok": true}'
 	else
-		response=`curl $MY_CURL_OPTIONS <<< "$TEXT"`
-		status=$?
+		if [ "$PASS_CAPTION" = true ]; then
+			response=`curl $MY_CURL_OPTIONS <<< "$TEXT"`
+			status=$?
+		else
+			response=`curl $MY_CURL_OPTIONS --verbose <<< "$MEDIA_JSON"`
+			status=$?
+		fi
 	fi
 	log "Response was: $response"
 	if [ $status -ne 0 ]; then
